language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - travis_retry composer update --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text
